fix: workflow (#32)

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -27,10 +27,10 @@ jobs:
       - name: Insert Key
         run: |
           echo ${{ secrets.FILEKEY }} >> filekey.key
-      - name: Sample and Download Json
+      - name: Sample and Download Json (1)
         run: |
           python sample_n_download.py data/package_names.txt ./download 1000
-      - name: Sample and Decrypt Json
+      - name: Sample and Decrypt Json (2)
         run: |
           python sample_n_decrypt.py data/latest ./decrypt 10000
       - name: Run JSkiner 1
@@ -56,7 +56,7 @@ jobs:
           git config --global user.email "jeffrey82221@gmail.com"
           git config --global user.name "jeffrey82221"
           git config pull.rebase false
-          git pull origin main
+          git pull origin main || echo 'pull failed'
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
